name: global_net
description: A new Flutter project.

version: 2.0.1

environment:
  sdk: ">=2.14.4 <=2.19.6" # ref 4d9e56e694

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dependencies:
  universal_html: 2.2.2
  sqflite: 2.2.8+4
  applovin_max: 2.5.0
  graphview: 1.1.1
  infinite_scroll_pagination: 3.2.0
  carousel_slider: 4.2.1
  firebase_core: 1.24.0
  cloud_firestore: 3.1.18
  paginate_firestore: 1.0.3+1
  firebase_auth: 3.11.2
  firebase_storage: 10.3.11
  firebase_messaging: 13.1.0
  http: 0.13.5
  dropdown_button2: 1.9.2
  image_picker: 0.8.5+3
  google_sign_in: 5.4.3
  flutter_signin_button: 2.0.0
  uuid: 3.0.7
  image: 3.2.2
  cupertino_icons: 1.0.5
  path_provider: 2.0.11
  flutter_svg: 1.1.6
  cached_network_image: 3.2.3
  timeago: 3.3.0
  material_design_icons_flutter: 6.0.7096
  font_awesome_flutter: 9.0.0
  flutter_svg_provider: 1.0.3
  fluttertoast: 8.1.2
  photo_view: 0.14.0
  container_tab_indicator: 0.3.0
  nb_utils: 4.6.25
  google_fonts: 3.0.1
  provider: 6.0.5
  story_view: 0.14.0
  flutter_staggered_grid_view: 0.4.0
  share_plus: 6.3.4
  url_launcher: 6.1.7
  flutter_linkify: 5.0.2
  simple_animations: 5.0.0+3
  ionicons: 0.2.1
  link_preview_generator: 1.2.0
  another_flushbar: 1.12.29
  fluttericon: 2.0.0
  flutter_reaction_button: 2.0.1+2
  file_picker: 5.2.4
  visibility_detector: 0.3.3
  filesize: 2.0.1
  easy_pdf_viewer: 1.0.6
  adaptive_theme: 3.1.1
  video_player: 2.4.10
  flick_video_player: 0.5.0
  string_validator: 0.3.0
  # google_mobile_ads: 2.3.0
  equatable: 2.0.5
  json_annotation: 4.7.0
  badges: 2.0.3
  iconly: 1.0.1
  video_compress: 3.1.2
  webview_flutter: 2.0.12
  flutter_mobx: 2.0.6+5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  geolocator: 10.1.0
  geocoding: 2.0.5
  giphy_get: 2.0.4
  in_app_purchase: 3.0.8
  scoped_model: 2.0.0
  sign_in_with_apple: 4.2.0
  crypto: 3.0.2
  flutter_local_notifications: 16.3.2
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: 1.1.0
  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.11.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/html/