// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCniC3TzeI8CjFPyJX_BI8fVYx3CDH_dr8",
      authDomain: "globelgirl-2c269.firebaseapp.com",
      databaseURL: "https://globelgirl-2c269-default-rtdb.firebaseio.com",
      projectId: "globelgirl-2c269",
      storageBucket: "globelgirl-2c269.appspot.com",
      messagingSenderId: "813756573374",
      appId: "1:813756573374:web:814522eaf85f06cc12a0ef",
      measurementId: "G-BH442MS22N"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx3Q1JEtUne8wWefRk2k1HkiaTBEduDMI',
    appId: '1:813756573374:android:327093530af0423c12a0ef',
    messagingSenderId: '813756573374',
    projectId: 'globelgirl-2c269',
    storageBucket: 'globelgirl-2c269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2MXV-1IGGNt1imJGhowKMBELh-1ayRM',
    appId: '1:560568355737:ios:77538d1971e3bd21d62108',
    messagingSenderId: '560568355737',
    projectId: 'x-x-x-test',
    storageBucket: 'x-x-x-test.appspot.com',
    iosClientId: '560568355737-itb1f7453lnt9s2mnjdtsk759d3dcpqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe2MXV-1IGGNt1imJGhowKMBELh-1ayRM',
    appId: '1:560568355737:ios:77538d1971e3bd21d62108',
    messagingSenderId: '560568355737',
    projectId: 'x-x-x-test',
    storageBucket: 'x-x-x-test.appspot.com',
    iosClientId: '560568355737-itb1f7453lnt9s2mnjdtsk759d3dcpqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
