name: Linux

on:
  push:
    branches: [ b-global.net.liru ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17" # java-version > 17 Error Execution failed for task ':video_player_android:compileReleaseJavaWithJavac'
          distribution: "jetbrains"

      - name: Setup flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.7.12

      - name: Flutter pub get
        run: flutter pub get

      - name: Fix Error The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.- 'Object' is from 'dart:core'. final parsed = css.parse(text);
        run: cp -rf .no_remove/element_subclasses.dart $PUB_CACHE/hosted/pub.dev/universal_html-2.2.2/lib/src/html/dom

      - name: Fix Error The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.- 'Object' is from 'dart:core'. final parsed = css.parse(text);
        run: cp -rf .no_remove/link_preview.dart $PUB_CACHE/hosted/pub.dev/link_preview_generator-1.2.0/lib/src/widgets
        
      - name: BUILD APK
        run: |
          flutter build apk --release --flavor mobile
          flutter build apk --release --flavor tv

      - name: BUILD AAB MOBILE
        run: |
          flutter build appbundle --release --flavor mobile
          flutter build appbundle --release --flavor tv

      - name: UPLOAD AAB AND APK
        run: |
          sudo tar --use-compress-program='xz -9' -cf /tmp/java.tar.xz $JAVA_HOME
          __APP_VERSION="v$($ANDROID_HOME/cmdline-tools/latest/bin/apkanalyzer manifest print "build/app/outputs/flutter-apk/app-mobile-release.apk" | grep versionName | cut -d'"' -f2)"
          gh release delete "${__APP_VERSION}" --yes || true
          gh release create "${__APP_VERSION}" --title "GGN" --latest=true --generate-notes || true
          gh release upload "${__APP_VERSION}" \
          build/app/outputs/bundle/mobileRelease/app-mobile-release.aab \
          build/app/outputs/bundle/tvRelease/app-tv-release.aab \
          build/app/outputs/flutter-apk/app-mobile-release.apk \
          build/app/outputs/flutter-apk/app-tv-release.apk \
          /tmp/java.tar.xz \
          --clobber

      - name: BUILD WEB AND DEPLOY
        run: |
          flutter build web --release --web-renderer html
          npm install -g firebase-tools
          firebase deploy --only hosting:globelgirl-2c269 --token "${{ secrets.FIREBASE_TOKEN }}"